version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chat
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 123123123
  adminer:
    image: adminer
    restart: always
    ports:
      - '8080:8080'
